apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sendbird-calls-sdk-react-native
  description: Calls SDK for React-Native (for release)
  annotations:
    github.com/project-slug: sendbird/sendbird-calls-sdk-react-native
spec:
  type: library
  lifecycle: production
  owner: dep-client-platform
  system: sendbird-calls
